all: compile
	@echo -e '[INFO] Done!'

clean:
	@echo -e '[INFO] Cleaning up...'
	@find . -name "*.class" -type f -delete

compile:
	@echo -e '[INFO] Compiling the source...'
	@javac cs455/overlay/node/Registry.java
	@javac cs455/overlay/node/MessagingNode.java
